config/routes.rb
Rails.application.routes.draw do
  post 'users/edit', to: 'users#update'
  put 'users/edit', to: 'users#update'
  get 'search', to: 'search#search'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'signup' },
                     controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users

  resources :projects do
    resources :tickets, shallow: true do
      resources :comments, only: %i[create destroy]
    end
  end

  namespace :admin do
    get 'admin/users', to: 'admin/users#index'
    resources :users
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_charts.html.erb
<div class="container-fluid">
  <div class="row">
      <div class="col-md-4 mb-2 mb-md-0">
        <div class="card">
          <div class="card-header d-flex justify-content-center">
            <h4 class="card-title mt-auto mb-auto"><%= t('strings.tickets.charts.by_attribute', attribute: Status.model_name.human) %></h4>
          </div>
          <div class="card-body">
            <canvas id="ticketsStatusChart" data-labels="<%= @statuses %>" data-tickets="<%= @ticket_statuses %>"></canvas> 
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-2 mb-md-0">
        <div class="card">
          <div class="card-header d-flex justify-content-center">
            <h4 class="card-title mt-auto mb-auto"><%= t('strings.tickets.charts.by_attribute', attribute: Priority.model_name.human) %></h4>
          </div>
          <div class="card-body">
            <canvas id="ticketsPriorityChart" data-labels="<%= @priorities %>" data-tickets="<%= @ticket_priorities %>"></canvas>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-2 mb-md-0">
        <div class="card">
          <div class="card-header d-flex justify-content-center">
            <h4 class="card-title mt-auto mb-auto"><%= t('strings.tickets.charts.by_attribute', attribute: Type.model_name.human) %></h4>
          </div>
          <div class="card-body">
            <canvas id="ticketsTypeChart" data-labels="<%= @types %>" data-tickets="<%= @ticket_types %>"></canvas>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/shared/_latest_projects.html.erb
<div class="latest-projects col-md-6 col-sm-12 mb-sm-2">
  <div class="card">
    <div class="card-header d-flex justify-content-center">
      <h4 class="card-title mt-auto mb-auto"><%= t('strings.resources.newest_resources', resource: Project.model_name.human) %></h4>
    </div>
    <div class="">
      <table class='content-table'>
        <thead class="text-uppercase">
          <tr>
            <th><%= Project.human_attribute_name('name') %></th>
            <th class='d-none d-sm-table-cell'><%= t('datetime.created_at') %></th>
            <th><%= Project.human_attribute_name('target_end_date') %></th>
          </tr>
        </thead>
          <tbody>
            <% unless @projects.empty? %>
              <% @projects.each do |p| %>
                <tr data-href=<%= project_url(p.id)%>>
                  <td><%= p.name %></td>
                  <td class='d-none d-sm-table-cell'><%= p.created_at.strftime("%Y/%m/%d %H:%M") %></td>
                  <td><%= p.target_end_date.strftime("%Y/%m/%d") %></td>
                </tr>
              <% end %>
            <% else %>
              <tr>
                <td colspan="2" class='text-center'><%= t('strings.resources.no_resource_yet', resource: Project.model_name.human.downcase) %></td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shared/_latest_tickets.html.erb
<div class="latest-tickets col-md-6 col-sm-12">
  <div class="card">
    <div class="card-header d-flex justify-content-center">
      <h4 class="card-title mt-auto mb-auto"><%= t('strings.resources.newest_resources', resource: Ticket.model_name.human) %></h4>
    </div>
    <div class="">
      <table class='content-table'>
        <thead class='text-uppercase'>
          <tr>
            <th><%= Ticket.human_attribute_name('title') %></th>
            <th class='d-none d-lg-table-cell'><%= t('strings.tickets.assigned_developer') %></th>
            <th><%= Ticket.human_attribute_name('status') %></th>
            <th class='d-none d-sm-table-cell'><%= Ticket.human_attribute_name('date_identified') %></th>
          </tr>
        </thead>
        <tbody>
          <% unless @tickets.empty? %>
            <% @tickets.each do |t| %>
              <tr data-href=<%= ticket_url(t.id) %>>
                <td><%= t.title %></td>
                <td class='d-none d-lg-table-cell'><%= t.user.name %></td>
                <td class='nowrap-column'><div class="status-pill-<%= t.status.id %>"><%= t.status.name %></div></td>
                <td class='d-none d-sm-table-cell'><%= t.created_at.strftime("%Y/%m/%d %H:%M") %></td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="4" class="text-center"><%= t('strings.resources.no_resource_yet', resource: Ticket.model_name.human) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shared/_messages.html.erb
<% unless flash.empty? %>
  <script>
    <% flash.each do |k, v| %>
      <% x = k.to_s.gsub('alert', 'error').gsub('notice', 'success') %>

        new Noty({
          type: '<%= x %>',
          layout: 'topCenter',
          theme: 'metroui',
          text: '<%= v %>',
          timeout: 3000,
          progressBar: false
        }).show();
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Topbar -->
<nav class="navbar navbar-expand-md navbar-light bg-light topbar mb-4 fixed-top ">
  <%= link_to  "Tracky", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topNav" aria-expanded='false'>
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="topNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to  t('links.home'), root_path, class: 'nav-link text-lg text-nowrap' %>
        </li>
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link text-lg text-nowrap" href="#" id='projectDropdown' role='button' data-toggle='dropdown' title="<%= t('links.projects') %>"><%= t('links.projects') %></a>
          <div class="dropdown-menu shadow animated--grow-in" aria-labelledby='projectDropdown'>
            <%= link_to  projects_path, class: 'dropdown-item' do %>
              <i class="fas fa-list-ul fa-sm fa-fw mr-2 text-gray-400"></i>
              <%= t('strings.resources.overview', resource: Project.model_name.human) %>
            <% end %>
              <%= link_to  new_project_path, class: 'dropdown-item text-nowrap' do %>
                <i class="fas fa-folder fa-sm fa-fw mr-2 text-gray-400"></i>
                <%= t('links.new_project') %>
            <% end %>
          </div>
        </li>
        <% if current_user.admin? %>
          <li class="nav-item">
            <%= link_to  t('links.users'), admin_users_path, class: 'nav-link text-lg text-nowrap' %>
          </li>
        <% end %>
      </ul>
      <div class="search-field ml-auto">
        <%= form_with url: search_path, local: true, method: :get, html: { class: 'form-inline my-2 my-lg-0' } do |f| %>
          <%= f.text_field :q, placeholder: t('strings.search'), data: { behaviour: 'autocomplete', header1: Project.model_name.human, header2: Ticket.model_name.human }, class: 'form-control mr-sm-2 search-input' %>
          <%= f.button t('strings.search'), class: 'btn my-2 my-sm-0 mx-2', id: 'search-button' do %>
            <i class="fas fa-search"></i>
          <% end %>
        <% end %>
      </div>
    </div> 


    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
      <% if !(user_signed_in?) %>
        <div class="d-sm-flex align-items-center justify-content-between">
          <%= link_to  t('links.login'), new_user_session_path, class: 'btn btn-sm btn-outline-primary' %>&nbsp;&nbsp;
          <%= link_to  t('links.signup'), new_user_registration_path, class: 'btn btn-sm btn-outline-primary' %>&nbsp;&nbsp;
        </div>
      <% else %>
        <div class="d-flex left-navbar">
        <!-- Language Selector -->
        <li class='nav-item dropleft no-arrow'>
          <a class='nav-link' href='#' id='languageDropdown' role='button'
             data-toggle='dropdown' title="<%= t('activerecord.models.locale') %>">
            <i class='fas fa-globe fa-lg fa-fw'></i>
          </a>
          <div class='dropdown-menu shadow animated--grow-in' aria-labelledby='languageDropdown'>
            <%= link_to t('activerecord.attributes.locale.english'), user_registration_path(id: current_user.id, 'user[locale_id]' => 1), method: :patch, class: 'dropdown-item' %>
            <%= link_to t('activerecord.attributes.locale.japanese'), user_registration_path(id: current_user.id, 'user[locale_id]' => 2), method: :patch, class: 'dropdown-item' %>
          </div>
        </li>
        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 ">
                <%= current_user.name %><br>
                <span class="text-gray-600 small"><%= current_user.role.title %>
                  <% if current_user.admin? %>
                    | <%= User.human_attribute_name('admin') %>
                  <% end %>
                </span>
                </span>
                <%= image_tag avatar(current_user), class: 'img-profile rounded-circle' %>
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <%= link_to  edit_user_registration_path(current_user), class: 'dropdown-item' do %>
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    <%= t('links.profile') %>
                <% end %>
                <div class="dropdown-divider"></div>
                <%= link_to  destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  <%= t('links.logout') %>
                <% end %>
            </div>
        </li>
        </div>
      <% end %>
    </ul>

</nav>

app/views/shared/_project_details.html.erb
<div class="project-info card">
  <div class="card-header d-flex justify-content-between">
    <h4 class="card-title mt-auto mb-auto"><%= t('strings.resources.details_with_id', resource: Project.model_name.human, id: @project.id) %></h4>
    <div class="inline">
      <%= link_to  projects_path, class: 'btn btn-circle btn-lg back-btn', title: t('links.overview', resource: Project.model_name.human), data: { toggle: 'tooltip', delay: { 'show': 300, 'hide': 100 } } do %>
        <i class="fas fa-list-ul"></i>
      <% end %>
      <%= link_to edit_project_path(@project), class: 'btn btn-circle btn-lg edit-btn', title: t('links.edit'), data: { toggle: 'tooltip', delay: { 'show': 300, 'hide': 100 } } do %>
        <i class="fas fa-pen"></i>
      <% end %>
      <%= link_to @project, method: :delete, title: t('links.delete'), data: { toggle: 'tooltip', delay: { 'show': 300, 'hide': 100 }, confirm: t('strings.resources.delete_really_dependents', resource: Project.model_name.human, dependent: Ticket.model_name.human)}, class: 'btn btn-circle btn-lg delete-btn' do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </div>
  </div>
  <div class="card-body">
    <div class="project-details row">
      <div class="container project-info col">
        <div class="row">
          <div class="col-sm">
            <p class="text-uppercase text-muted"><%= Project.human_attribute_name('name') %></p>
            <%= @project.name %>
          </div>
          <div class="col-sm">
            <p class="text-uppercase text-muted"><%= Project.human_attribute_name('description') %></p>
            <%= @project.description %>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm">
            <p class="text-uppercase text-muted"><%= Project.human_attribute_name('start_date') %></p>
            <%= @project.start_date.strftime("%Y/%m/%d") %>
          </div>
          <div class="col-sm">
            <p class="text-uppercase text-muted"><%= Project.human_attribute_name('target_end_date') %></p>
            <%= @project.target_end_date.strftime("%Y/%m/%d") %>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm">
            <p class="text-uppercase text-muted"><%= t('datetime.created_at') %></p>
            <%= @project.created_at.strftime("%Y/%m/%d %H:%M") %>
          </div>
          <div class="col-sm">
            <p class="text-uppercase text-muted"><%= Ticket.human_attribute_name('submitted_by') %></p>
            <%= @project.user.name %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_project_tickets.html.erb
<div class="ticket-info card">
  <div class="card-header d-flex justify-content-between">
    <div>
      <h4 class="card-title"><%= t('strings.projects.tickets_for') %></h4>
      <h5 class="card-subtitle text-muted"><%= t('strings.tickets.condensed_details') %></h5>
    </div>
    <div>
      <%= link_to new_project_ticket_path(@project), class: 'btn btn-circle btn-lg add-btn', title: t('links.add'), data: { toggle: 'tooltip', delay: { 'show': 300, 'hide': 100 } } do %>
        <i class="fas fa-plus"></i>
      <% end %>
    </div>
  </div>
  <div class="">
    <table class='content-table table-sortable'>
      <thead class='text-uppercase'>
        <tr>
          <th><%= Ticket.human_attribute_name('title') %></th>
          <th class='d-none d-xl-table-cell'><%= Ticket.human_attribute_name('submitted_by') %></th>
          <th class='d-none d-lg-table-cell'><%= t('strings.tickets.assigned_developer') %></th>
          <th><%= Ticket.human_attribute_name('status') %></th>
          <th class='d-none d-sm-table-cell'><%= Ticket.human_attribute_name('date_identified') %></th>
        </tr>
      </thead>
      <tbody>
        <% unless @tickets.empty? %>
          <% @tickets.each do |t| %>
            <tr data-href=<%= ticket_url(t.id) %>>
              <td><%= t.title %></td>
              <td class='d-none d-xl-table-cell'><%= t.submitted_by %></td>
              <td class='d-none d-lg-table-cell'><%= t.user.name %></td>
              <td id='stat-column'><div class="status-pill-<%= t.status.id %>"><%= t.status.name %></div></td>
              <td class='d-none d-sm-table-cell'><%= t.created_at.strftime("%Y/%m/%d %H:%M") %></td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="5" class="text-center"><%= t('strings.resources.no_resource_yet', resource: Ticket.model_name.human) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate(@tickets, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'd-flex justify-content-center') %>
  </div>
</div>

app/views/shared/_ticket_comments.html.erb
<div class="col-md-6 mb-2 mb-md-0">
  <div class="card">
    <div class="card-header d-flex">
      <h4 class="card-title mt-auto mb-auto"><%= t('strings.comments.name') %></h4>
    </div>
    <div class="">
      <div class="ticket-comments-form form-inline">
        <%= form_with(model: @comment, url: ticket_comments_path(@ticket), method: :post, local: true) do |f| %>
          <%= f.text_field :message, placeholder: t('strings.comments.add_comment'), class: 'form-control' %>
          <%= button_tag(class: 'btn btn-circle ok-btn', title: t('links.save'), data: { toggle: 'tooltip', delay: { 'show': 300, 'hide': 100 } }) do %>
              <i class="fas fa-check"></i>
            <% end %>
        <% end %>
      </div>
      <div class="ticket-comments">
        <table class='content-table table-sortable'>
          <thead class="text-uppercase">
            <tr>
              <th><%= Comment.human_attribute_name('commenter') %></th>
              <th><%= Comment.human_attribute_name('message') %></th>
              <th class="d-none d-md-table-cell"><%= t('datetime.created_at') %></th>
              <td></td>
            </tr>
          </thead>
            <tbody>
              <% unless @comments.empty? %>
                <% @comments.each do |c| %>
                  <tr>
                    <td><%= c.commenter %></td>
                    <td><%= c.message %></td>
                    <td class="d-none d-md-table-cell"><%= c.created_at.strftime("%Y/%m/%d %H:%M") %></td>
                    <td>
                    <%= link_to comment_path(c.id), method: :delete, title: t('links.delete'), data: { toggle: 'tooltip', delay: { 'show': 300, 'hide': 100 }, confirm: t('strings.resources.delete_really') }, class: 'btn btn-circle delete-btn btn-sm' do %>
                        <i class="fas fa-trash"></i>
                    <% end %>
                    </td>
                  </tr>
                <% end %>
              <% else %>
                <tr>
                  <td colspan="4" class='text-center'><%= t('strings.resources.no_resource_yet', resource: Comment.model_name.human.downcase) %></td>
                </tr>
              <% end %>
            </tbody>
        </table>
        <%= will_paginate(@comments, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'd-flex justify-content-center') %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_ticket_info.html.erb
<div class="col-md-6 mb-2 mb-md-0">
  <div class="ticket-info card">
    <div class="card-header d-flex justify-content-between">
      <h4 class="card-title my-auto"><%= t('strings.resources.details_with_id', resource: Ticket.model_name.human, id: @ticket.id) %></h4>
      <div class="inline">
        <%= link_to project_path(@ticket.project_id), class: 'btn btn-circle back-btn btn-lg', data: { toggle: 'tooltip', delay: { 'show': 300, 'hide': 100 } }, title: t('links.back_to', resource: Project.model_name.human) do%>
          <i class="fas fa-arrow-left"></i>
        <% end %>
        <%= link_to edit_ticket_path(@ticket), class: 'btn btn-circle edit-btn btn-lg', data: { toggle: 'tooltip', delay: { 'show': 300, 'hide': 100 } }, title: t('links.edit') do %>
          <i class="fas fa-pen"></i>
        <% end %>
        <%= link_to @ticket, method: :delete, title: t('links.delete'), data: { toggle: 'tooltip', delay: { 'show': 300, 'hide': 100 }, confirm: t('strings.resources.delete_really_dependents', resource: Ticket.model_name.human, dependent: Comment.model_name.human) }, class: 'btn btn-circle delete-btn btn-lg' do %>
            <i class="fas fa-trash"></i>
        <% end %>
      </div>
    </div>
    <div class="card-body">
      <div class="ticket-details row">
        <div class="container ticket-info col">
          <div class="row">
            <div class="col-sm">
              <p class="text-uppercase text-muted"><%= Ticket.human_attribute_name('title') %></p>
              <%= @ticket.title %>
            </div>
            <div class="col-sm">
              <p class="text-uppercase text-muted"><%= Ticket.human_attribute_name('description') %></p>
              <%= @ticket.description %>
            </div>
          </div>
            <hr>
          <div class="row">
            <div class="col-sm">
              <p class="text-uppercase text-muted"><%= t('strings.tickets.assigned_developer') %></p>
              <%= @ticket.user.name %>
            </div>
            <div class="col-sm">
              <p class="text-uppercase text-muted"><%= Ticket.human_attribute_name('submitted_by') %></p>
              <%= @ticket.submitted_by %>
            </div>
          </div>
            <hr>
          <div class="row">
            <div class="col-sm">
              <p class="text-uppercase text-muted"><%= Project.model_name.human %></p>
              <%= link_to @ticket.project.name, project_path(@ticket.project.id) %>
            </div>
            <div class="col-sm">
              <p class="text-uppercase text-muted"><%= Ticket.human_attribute_name('priority') %></p>
              <div class="priority-pill-<%= @ticket.priority.id %> show-ticket-priority"><%= @ticket.priority.name %></div>
            </div>
          </div>
            <hr>
          <div class="row">
            <div class="col-sm">
              <p class="text-uppercase text-muted"><%= Ticket.human_attribute_name('status') %></p>
              <div class="status-pill-<%= @ticket.status.id %> show-ticket-status"><%= @ticket.status.name %></div>
            </div>
            <div class="col-sm">
              <p class="text-uppercase text-muted"><%= Ticket.human_attribute_name('type') %></p>
              <% if @ticket.type %>
                <div class="type-pill-<%= @ticket.type.id %> show-ticket-type"><%= @ticket.type.name %></div>
              <% else %>
                <p><%= t('strings.resources.no_resource_defined_yet', resource: Type.model_name.human) %></p>
              <% end %>
            </div>
          </div>
            <hr>
          <div class="row">
            <div class="col-sm">
              <p class="text-uppercase text-muted"><%= t('datetime.created_at') %></p>
              <%= @ticket.created_at.strftime("%Y/%m/%d %H:%M") %>
            </div>
            <div class="col-sm">
              <p class="text-uppercase text-muted"><%= t('datetime.updated_at') %></p>
              <%= @ticket.updated_at.strftime("%Y/%m/%d %H:%M") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>