config/routes.rb
Rails.application.routes.draw do
  post 'users/edit', to: 'users#update'
  put 'users/edit', to: 'users#update'
  get 'search', to: 'search#search'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'signup' },
                     controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users

  resources :projects do
    resources :tickets, shallow: true do
      resources :comments, only: %i[create destroy]
    end
  end

  namespace :admin do
    get 'admin/users', to: 'admin/users#index'
    resources :users
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :project
  belongs_to :status
  belongs_to :priority
  belongs_to :type

  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true
  validates :date_identified, presence: true
  validates :target_resolution_date, presence: true 
  validates :status_id, presence: true
  validates :priority_id, presence: true
  validates :type_id, presence: true
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[new create index]
  before_action :set_ticket, except: %i[new create index]
  before_action :get_comments, only: [:show]

  def new
    @ticket = @project.tickets.build
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    @ticket.submitted_by = current_user.name
    if @ticket.save
      flash[:notice] = t('strings.resources.created', resource: Ticket.model_name.human)
      redirect_to @ticket
    else
      flash[:alert] = @ticket.errors.full_messages
      render 'new'
    end
  end

  def index
    @tickets = Ticket.where(project_id: @project.id)
  end

  def update
    if @ticket.update(ticket_params)
      flash[:success] = t('strings.resources.updated', resource: Ticket.model_name.human)
      redirect_to @ticket
    else
      render 'edit'
    end
  end

  def destroy
    @project = @ticket.project
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to @project, notice: t('strings.resources.deleted', resource: Ticket.model_name.human) }
    end
  end

  private

  def set_project
    @project = Project.where(user_id: current_user.id).find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = t('strings.resources.not_found', resource: Project.model_name.human)
    redirect_to root_path
  end

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def get_comments
    @comments = Comment.where(ticket_id: @ticket.id).paginate(page: params[:page], per_page: 5)
  end

  def ticket_params
    params.require(:ticket).permit(:title, :description, :date_identified, :submitted_by, :related_project_id, :status_id, :priority_id, :type_id,
                                   :target_resolution_date, :actual_resolution_date, :resolution_summary, :updated_by, :user_id)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/edit.html.erb
<div class="container">
  <div class="card">
    <div class="card-header d-flex">
      <h5 class="card-title mt-auto mb-auto"><%= t('strings.resources.edit_resource_with_id', resource: Ticket.model_name.human, id: @ticket.id) %></h5>
    </div>
    <div class="card-body">
      <%= form_with(model: @ticket, method: :put, local: true) do |f| %>
        <div class="form-group col-12">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control mb-3' %>
        </div>
        <div class="form-group col-lg">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control mb-3' %>
        </div>
        <div class="form-group col-lg">
          <%= f.label :date_identified %>
          <%= f.date_field :date_identified, class: 'form-control mb-3' %>
        </div>
        <div class="form-group col-lg">
          <div class="row">
            <div class="col-md">
              <%= f.label :priority %>
              <%= f.select :priority_id, Priority.all.collect{ |p| [ p.name, p.id ] }, {}, class: 'form-control custom-select mb-3' %>
            </div>
            <div class="col-md">
              <%= f.label :status %>
              <%= f.select :status_id, Status.all.collect{ |s| [ s.name, s.id ] }, {}, class: 'form-control custom-select mb-3' %>
            </div>
            <div class="col-md">
              <%= f.label :type %>
              <%= f.select :type_id, Type.all.collect{ |t| [ t.name, t.id ] }, {}, class: 'form-control custom-select mb-3' %>
            </div>
          </div>
        </div>
        <div class="form-group col-lg">
          <%= f.label :user_id, t('strings.tickets.assigned_developer') %>
          <%= f.select :user_id, User.where(role_id: 1).collect{ |u| [ u.name, u.id ] }, {}, class: 'form-control custom-select' %>
        </div>
        <div class="form-group col-lg">
          <%= f.label :target_resolution_date %>
          <%= f.date_field :target_resolution_date, class: 'form-control mb-3' %>
        </div>
        
        <div class="form-group mt-2 d-flex justify-content-center">
          <%= button_tag(class: 'btn btn-circle ok-btn btn-lg', title: t('links.save'), data: { toggle: 'tooltip', delay: { 'show': 300, 'hide': 100 } }) do %>
                  <i class="fas fa-check"></i>
          <% end %>

          <%= link_to @ticket, class: 'btn btn-circle delete-btn btn-lg', title: t('links.delete'), data: { toggle: 'tooltip', delay: { 'show': 300, 'hide': 100 } } do %>
            <i class="fas fa-times"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tickets/index.html.erb
<div class="container">
  <h1 class='text-capitalize'>Tickets for <%= @project.name %></h1>
  <%= link_to  "Back to Project Overview", @project %>

  <table class='content-table table-sortable'>
    <thead class='text-uppercase'>
      <tr>
        <th><%= Ticket.human_attribute_name('title') %></th>
        <th><%= t('datetime.created_at') %></th>
        <th><%= t('strings.tickets.assigned_developer') %></th>
        <th><%= Ticket.human_attribute_name('status') %></th>
        <th><%= Ticket.human_attribute_name('priority') %></th>
        <th></th>
      </tr>
    </thead>
    <% @tickets.each do |t| %>
    <tbody>
      <tr>
        <td><%= t.title %></td>
        <td><%= t.date_identified %></td>
        <td><%= t.user.name %></td>
        <td><%= t.status.name %></td>
        <td><%= t.priority.name %></td>
        <td>
          <%= link_to ticket_path(t.id), class: 'btn-sm btn-secondary btn-icon-split text-decoration-none' do %>
            <div class="icon">
              <div class="fas fa-info-circle"></div>
            </div>
            <div class="text">Details</div>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>

  </table>
</div>

app/views/tickets/new.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">
        <%= t('strings.resources.add_resource', resource: Ticket.model_name.human) %>
      </h4>
      <h5 class="card-subtitle">
        <%= t('strings.tickets.added_to_project', name: @project.name) %>
      </h5>
    </div>
    <div class="card-body">
      <%= form_with(model: @ticket, url: project_tickets_path, method: :post, local: true) do |f| %>
        <div class="form-group col-lg">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group col-lg">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <div class="form-group col-lg">
          <%= f.label :date_identified %>
          <%= f.date_field :date_identified, class: 'form-control' %>
        </div>
        <div class="form-group col-lg">
          <div class="row">
            <div class="col-md mb-3 mb-md-0">
              <%= f.label :priority %>
              <%= f.select :priority_id, Priority.all.collect{ |p| [ p.name, p.id ] }, {}, class: 'form-control custom-select' %>
            </div>
            <div class="col-md mb-3 mb-md-0">
              <%= f.label :status %>
              <%= f.select :status_id, Status.all.collect{ |s| [ s.name, s.id ] }, {}, class: 'form-control custom-select' %>
            </div>
            <div class="col-md">
              <%= f.label :type %>
              <%= f.select :type_id, Type.all.collect{ |t| [ t.name, t.id ] }, {}, class: 'form-control custom-select' %>
            </div>
          </div>
        </div>
        <div class="form-group col-lg">
          <%= f.label :user_id, t('strings.tickets.assigned_developer') %>
          <%= f.select :user_id, User.where(role_id: 1).collect{ |u| [u.name, u.id ] }, {}, class: 'form-control custom-select' %>
        </div>
        <div class="form-group col-lg">
          <%= f.label :target_resolution_date %>
          <%= f.date_field :target_resolution_date, class: 'form-control' %>
        </div>

        <div class="form-group mt-2 d-flex justify-content-center">
          <%= button_tag(class: 'btn btn-circle ok-btn btn-lg', title: t('links.save'), data: { toggle: 'tooltip', delay: { 'show': 300, 'hide': 100 } }) do %>
            <i class="fas fa-check"></i>
          <% end %>

          <%= link_to @project, class: 'btn btn-circle delete-btn btn-lg', title: t('links.cancel'), data: { toggle: 'tooltip', delay: { 'show': 300, 'hide': 100 } } do %>
            <i class="fas fa-times"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tickets/show.html.erb
<div class="container-fluid">
  <div class="row row-cols-1 row-cols-md-2">
    <%= render 'shared/ticket_info' %>
    <%= render 'shared/ticket_comments' %>
  </div>
</div>